# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: 'libraries/ui/'
repos:
  - repo: https://github.com/igrr/astyle_py.git
    rev: v1.0.5
    hooks:
      - id: astyle_py
        args: ['--style=otbs', '--attach-namespaces', '--attach-classes', '--indent=spaces=4', '--convert-tabs', '--align-pointer=name', '--align-reference=name', '--keep-one-line-statements', '--pad-header', '--pad-oper']

  - repo: https://github.com/espressif/check-copyright/
    rev: v1.0.3
    hooks:
      - id: check-copyright
        args: ['--config', 'check_copyright_config.yaml']

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        types: [python]
        args: ['--config=.flake8', '--tee', '--benchmark']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        # note: whitespace exclusions use multiline regex, see https://pre-commit.com/#regular-expressions
        # items are:
        # 1 - some file extensions
        # 2 - any file matching *test*/*expected* (for host tests, if possible use this naming pattern always)
        # 3 - any file with known-warnings in the name
        # 4 - any directory named 'testdata'
        # 5 - protobuf auto-generated files
        exclude: &whitespace_excludes |
          (?x)^(
            .+\.(md|rst|map|bin)|
            .+test.*\/.*expected.*|
            .+known-warnings.*|
            .+\/testdata\/.+|
            .*_pb2.py|
            .*.pb-c.h|
            .*.pb-c.c|
            .*.yuv
          )$
      - id: end-of-file-fixer
        exclude: *whitespace_excludes
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
        args: ['-f=lf']
      - id: double-quote-string-fixer
      - id: no-commit-to-branch
        name: Do not use more than one slash in the branch name
        args: ['--pattern', '^[^/]*/[^/]*/']
      - id: no-commit-to-branch
        name: Do not use uppercase letters in the branch name
        args: ['--pattern', '^[^A-Z]*[A-Z]']

  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.8.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
        args:
          - --subject-min-length=15
          - --body-max-line-length=200

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      args: ['-w' , '--config', '.codespellrc']

  - repo: local
    hooks:
      - id: check-library-versions
        name: Check library versions
        entry: ./.github/scripts/check_lib_versions.sh
        language: system
        files: '(idf_component.yml|library.properties)'
